framework:
    csrf_protection: ~

security:
    providers:
        admin_db_provider:
            entity:
                class: App\Entity\Admin
                property: username
        in_memory: { memory: ~ }

    encoders:
        App\Entity\Admin:
            algorithm: bcrypt
            cost: 12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            provider: admin_db_provider
            form_login:
                csrf_token_generator: security.csrf.token_manager
                login_path: login
                check_path: post_login
                failure_path: login
                default_target_path: admin_dashboard
            logout:
                path: /logout
                target: /

            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/dashboard, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
